# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title Function to compute least-squares boosting and the p-value
#' 
#' @description This function computes the LS-Boost estimates, the standard errors, and 
#'   the p-values for a cross-section regression model.
#'   
#' @param y The n by 1 vector of the dependent variable. 
#' @param x The n by p matrix of the independent variables.
#' @param bstop The number of boosting steps. Defaults to 50.
#' @param nu The learning rate. Defaults to 0.1.
#' @return The \code{boostlscpp} function returns a list with the following components:
#'   \item{y}{The n by 1 vector of the dependent variable.}
#'   \item{x}{The n by p matrix of the independent variables.}
#'   \item{bstop}{The number of boosting steps.}
#'   \item{beta}{The p by bstop matrix of parameter estimates in all boosting steps.}
#'   \item{beta0}{The bstop by 1 vector of intercept estimates in all boosting steps.}
#'   \item{se}{The p by bstop matrix of standard errors in all boosting steps.}
#'   \item{pval}{The p by bstop matrix of p-values for all parameter estimates in all
#'         boosting steps. If a p-value is equal to 1, it means the corresponding parameter has
#'         not been updated up to that boosting step.}
#'   \item{step_mat}{A p by bstop matrix that records which variable is updated at each
#'         boosting step.}
#'   \item{aic}{A sequence of AIC values of length \code{bstop}.}
boostlscpp <- function(y, x, bstop = 50L, nu = 0.1) {
    .Call('_boostvar_boostlscpp', PACKAGE = 'boostvar', y, x, bstop, nu)
}

#' @title CPP function for the first group boosting method in Huang (2022)
#' 
#' @description This function computes the LS-Boost1 estimates and their 
#'   p-values. 
#' 
#' @param datay An n by d matrix of variables with n observations and d variables.
#'   n is the number of time periods in the data, where the first row gives the
#'   first observation and the last row includes the most recent observation.
#' @param p A positive integer for the lag of VAR. Defaults to 1.
#' @param bstop The number of boosting steps. Defaults to 50.
#' @param nu The learning rate. Defaults to 0.1.
#' @return \code{lsboost1} returns a list with the following components: \itemize{
#' \item y: The (n-p)*d matrix of the dependent variable on the left hand side of the 
#'   regression equation.
#' \item x: The d(n-p)*p matrix of the X matrix. Each (n-p)*p block includes the
#'   p lags of a variable. Each lag is an (n-p)*1 column.
#' \item aic: A sequence of AIC values of length \code{bstop}.
#' \item df: A sequence of degree of freedom estimates of length \code{bstop}.
#' \item beta_mat: A \eqn{bstop*d*p} by d matrix of coefficient estimates. It stacks
#'   all \code{bstop} \eqn{\phi_{g}} coefficient matrices in equation (7) in Huang (2022).
#' \item se_mat: A matrix of standard errors for \code{beta_mat}.
#' \item pval_mat: A matrix of p-values for \code{beta_mat}.
#' \item beta0_mat: A \eqn{d*bstop} matrix of intercept estimates for each boosting step.
#' \item step_mat: A \eqn{d*bstop} matrix that records which variable is updated at 
#'   each boosting step.
#' }
#' 
#' @examples
#' \dontrun{
#'   # An example of bivariate vector autoregression
#'   library(boostvar)
#'   set.seed(123)
#'   p = 2
#'   d = 2
#'   nobs = 100
#'   bstop = 50
#'   y = matrix(0, nobs, d)
#'   b0 = matrix(c(0.02,0.03),2,1)
#'   b1 = matrix(c(0.5,0.4,0.1,0.5),2,2)
#'   b2 = matrix(c(0,0.25,0,0),2,2)
#'   for (i in 3:dim(y)[1]) {
#'     y[i,] = t(b0) + t(b1 %*%  y[i-1,]) + t(b2 %*% y[i-2,]) +
#'       c(rnorm(1,0,0.3), rnorm(1,0,0.2))
#'   }
#'   y = tail(y,-p)
#'   result = lsboost1(y, p = p, bstop = bstop, nu = 0.1)
#'   }
lsboost1 <- function(datay, p = 1L, bstop = 50L, nu = 0.1) {
    .Call('_boostvar_lsboost1', PACKAGE = 'boostvar', datay, p, bstop, nu)
}

#' @title CPP function for the second group boosting method in Huang (2022)
#' 
#' @description This function computes the LS-Boost2 estimates and their 
#'   p-values. 
#' 
#' @param datay An n by d matrix of variables with n observations and d variables.
#'   n is the number of time periods in the data, where the first row gives the
#'   first observation and the last row includes the most recent observation.
#' @param p A positive integer for the lag of VAR. Defaults to 1.
#' @param bstop The number of boosting steps. Defaults to 50.
#' @param nu The learning rate. Defaults to 0.1.
#' @return \code{lsboost2} returns a list with the following components: \itemize{
#' \item y: The (n-p)*d matrix of the dependent variable on the left hand side of the 
#'   regression equation.
#' \item x: The d(n-p)*p matrix of the X matrix. Each (n-p)*p block includes the
#'   p lags of a variable. Each lag is an (n-p)*1 column.
#' \item aic: A sequence of AIC values of length \code{bstop}.
#' \item df: A sequence of degree of freedom estimates of length \code{bstop}.
#' \item beta_mat: A \eqn{bstop*d*p} by d matrix of coefficient estimates. It stacks
#'   all \code{bstop} \eqn{\phi_{g}} coefficient matrices in equation (7) in Huang (2022).
#' \item se_mat: A matrix of standard errors for \code{beta_mat}.
#' \item pval_mat: A matrix of p-values for \code{beta_mat}.
#' \item beta0_mat: A \eqn{d*bstop} matrix of intercept estimates for each boosting step.
#' \item step_mat: A \eqn{d^2*bstop} matrix that records which variable is updated at 
#'   each boosting step.
#' }
#' @examples
#' \dontrun{
#'   # An example of bivariate vector autoregression
#'   library(boostvar)
#'   set.seed(123)
#'   p = 2
#'   d = 2
#'   nobs = 100
#'   bstop = 50
#'   y = matrix(0, nobs, d)
#'   b0 = matrix(c(0.02,0.03),2,1)
#'   b1 = matrix(c(0.5,0.4,0.1,0.5),2,2)
#'   b2 = matrix(c(0,0.25,0,0),2,2)
#'   for (i in 3:dim(y)[1]) {
#'     y[i,] = t(b0) + t(b1 %*%  y[i-1,]) + t(b2 %*% y[i-2,]) +
#'       c(rnorm(1,0,0.3), rnorm(1,0,0.2))
#'   }
#'   y = tail(y,-p)
#'   result = lsboost2(y, p = p, bstop = bstop, nu = 0.1)
#'   }
lsboost2 <- function(datay, p = 1L, bstop = 50L, nu = 0.1) {
    .Call('_boostvar_lsboost2', PACKAGE = 'boostvar', datay, p, bstop, nu)
}

